[package]
name = "mongo-collections"
version = "1.0.0"
edition = "2024"
default-run = "mongo-collections"
description = "The MongoDB collections operator"
homepage = "https://github.com/wdonne/mongo-collections"
repository = "https://github.com/wdonne/mongo-collections"
license = "BSD-2-Clause"
readme = "README.md"
keywords = ["kubernetes", "operator", "mongodb", "collections"]
exclude = ["*.iml"]

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "resource"
path = "src/resource.rs"

[dependencies]
kube = { version = "2.0.1", features = ["runtime", "derive", "client"] }
k8s-openapi = { version = "0.26.0", features = ["v1_30"] }
schemars = "1.1.0"
serde = "1.0.228"
serde_json = "1.0.145"
kube-operator-util = "1.0.0"
generic-builders = "1.0.0"
tokio = { version = "1.48.0", features = ["full"] }
log = "0.4.28"
thiserror = "2.0.17"
anyhow = "1.0.100"
futures = "0.3.31"
rustls = { version = "0.23.35", features = ["ring"] }
env_logger = "0.11.8"
mongodb = { version = "3.3.0", features = ["aws-auth"] }
config = "0.15.18"
serde_repr = "0.1.20"
